#!/usr/bin/env python3
""" ldir - Утилита командной строки для работы с файлами и каталогами."""

from __future__ import annotations
from typing import Optional
from dataclasses import dataclass
import os
import argparse
import shutil
import subprocess
import tempfile
import uuid
from datetime import datetime
from pathlib import Path

from modules.app import app


def main() -> None:
    """точка входа"""


if __name__ == "__main__":
    main()
